### ISSUE TITLE
Cannot build a plugin after upgrading to angular@11

### ISSUE THREAD

**Issue by irahov** [vmware/vcd-ext-sdk#212]
**Describe the bug**
Cannot build a plugin after an upgrade to angular@11.
Got an error:
`[error] TypeError: browser_1.buildBrowserWebpackConfigFromContext is not a function`

**To Reproduce**
1. Create a new plugin `vcd-ext new` https://vmware.github.io/vcd-ext-sdk/docs/ui_plugins/getting_started
2. Upgrade angular from `v9` the preinstalled one to `v11`
`npx ng update --force @angular/core@11 @angular/cli@11`
3.  Run `npm run build`, See error
```
[error] TypeError: browser_1.buildBrowserWebpackConfigFromContext is not a function
    at /Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@vcd/plugin-builders/base/index.js:52:41
    at Generator.next (<anonymous>)
    at /Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@vcd/plugin-builders/base/index.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@vcd/plugin-builders/base/index.js:9:12)
    at commandBuilder (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@vcd/plugin-builders/base/index.js:47:12)
    at onInput (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/src/create-builder.js:150:30)
    at SafeSubscriber._next (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/src/create-builder.js:64:29)
    at SafeSubscriber.__tryOrUnsub (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Object.next (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/observable/onErrorResumeNext.js:22:49)
    at SafeSubscriber.__tryOrUnsub (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Users/irahov/workspace/vmware-gitlab/IrTestSolution/packages/irUiPlugin/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:89:26)
```
** Expected**
There should be clear info about angular the dependencies or (maybe even better) `@vcd/ext-cli` version per vcd release

**Comment by nvladimirovi** [comment]
We are not currently supporting Angular 11 yet.
